config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :group, only: [:index, :new, :create] do
    resources :entities, only: [:index, :new, :create]
  end
  root to: 'group#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, author: user
    can :manage, Entity, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :group_entities
  has_many :groups, through: :group_entities

  validates :name, presence: true, length: { in: 4..250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :group_entities
  has_many :entities, through: :group_entities

  validates :name, presence: true, length: { in: 4..250 }
  validates :icon, presence: true, length: { in: 4..250 }
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: :author_id
  has_many :groups, foreign_key: :author_id

  validates :name, presence: true, length: { in: 4..250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @group = current_user.groups.find(params[:group_id])
    @entities = @group.entities
  end

  def new
    @group = current_user.groups.find(params[:group_id])
    @entity = @group.entities.new
  end

  def create
    @group = current_user.groups.find(params[:group_id])
    @entity = current_user.entities.create(entity_params)
    puts @entity
    if @entity.save
      @group_entity = @entity.group_entities.create(group_id: @group.id, entity_id: @entity.id)
      if @group_entity.save
        flash[:notice] = 'New transaction created successfully'
        redirect_to group_entities_path(@group)
      else
        flash.now[:alert] = 'Transaction category creation failed'
        render action: 'new'
      end
    else
      flash.now[:alert] = 'Transaction creation failed'
      render action: 'new'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @groups = current_user.groups
    else
      render 'users/splash'
    end
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @user = current_user
    @group = @user.groups.create(group_params)
    if @group.save
      flash[:notice] = 'New category created successfully'
      redirect_to group_index_path
    else
      flash.now[:alert] = 'Category creation failed'
      render action: 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/index.html.erb
<div class="min_nav">
  <%= link_to "", group_index_path, class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">Transactions</h3>
</div>
<div class="card mb-2">
  <div class="card-body d-flex justify-content-between align-items-center">
    <%= image_tag @group.icon || "http://localhost:3000/users/sign_up.jpg", class: 'card_icon' %>
    <div>
      <p class="fw-semibold"><%= @group.name %></p>
      <p class="fw-light"><%= l @group.created_at, format: :long %></p>
    </div>
    <p class="fw-bolder">
      $<%= @group.entities.sum(&:amount) %>
    </p>
  </div>
</div>
<% if @entities.count > 0 %>
  <% @entities.order(created_at: :desc).limit(4).each do |entity| %>
    <div class="card mb-2">
      <div class="card-body d-flex justify-content-between align-items-center">
        <div>
          <p class="fw-semibold"><%= entity.name %></p>
          <p class="fw-light"><%= l entity.created_at, format: :long %></p>
        </div>
        <p class="fw-bolder">
          $<%= entity.amount %>
        </p>
      </div>
    </div>
  <% end %>
<% else %>
  <p>You have no Transactions and new to continue</p>
<% end %>
<%= link_to 'Add Transaction', new_group_entity_path(@group), class: "btn btn-primary fixed-bottom" %>

app/views/entities/new.html.erb
<div class="min_nav">
  <%= link_to "", group_entities_path(@group), class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">New Transaction</h3>
</div>
<%= form_with model: @entity, url: group_entities_path, method: :post, data: { turbo: false } do |form| %>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Transaction name' %>
  </div>
  <div class="mb-3">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: 'form-control', placeholder: 12, type: "number", step: ".01" %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/group/index.html.erb
<h3 class="mb-3">Categories</h3>

<% if @groups.count > 0 %>
  <% @groups.each do |group| %>
    <%= link_to group_entities_path(group), class: "card mb-2" do %>
      <div class="card-body d-flex justify-content-between align-items-center">
        <%= image_tag group.icon || "http://localhost:3000/users/sign_up.jpg", class: 'card_icon' %>
        <div>
          <p class="fw-semibold"><%= group.name %></p>
          <p class="fw-light"><%= l group.created_at, format: :long %></p>
        </div>
        <p class="fw-bolder">
          $<%= group.entities.sum(&:amount) %>
        </p>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>You have no categories and new to continue</p>
<% end %>
<%= link_to 'Add Category', new_group_path, class: "btn btn-primary fixed-bottom" %>

app/views/group/new.html.erb
<div class="min_nav">
  <%= link_to "", group_index_path, class: "fa fa-chevron-left fa-lg" %>
  <h3 class="mb-3">Categories</h3>
</div>
<%= form_with model: @group, url: group_index_path, method: :post, data: { turbo: false } do |form| %>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Category name' %>
  </div>
  <div class="mb-3">
    <%= form.label :icon %>
    <%= form.url_field :icon, class: 'form-control', placeholder: 'Icon url' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Create category', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/23435c9c01.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render partial: 'shared/navbar' %>
<div class="container body">
  <%= render partial: 'shared/flash' %>
  <%= yield %>
</div>
</body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mt-4" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="navbar-brand"> Wallet App</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-warning' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/splash.html.erb
<div class="d-flex flex-column justify-content-center align-items-center mt-4">
  <h1 class="h1 text-primary mt-4">Wallet App</h1>
  <%= link_to "Sign In", new_user_session_path, class: 'btn-outline-primary mt-4' %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary mt-2' %>
</div>